<template>
    <div>
      <div>
        <div  v-for="(category,index) in categorys" :key="category.id">
          <span @click="show(index)" >{{category.name}}</span>
        <div v-if="showList[index]">
          <div v-for="(son,index2) in category.sons" :key="son.id">
            <span @click="show2(index,index2)"> {{son.name}}</span>
            <div v-if="showList2[index] != undefined ? showList2[index][index2] : false">
              <div v-for="(grandSon,index3) in son.grandSon" :key="grandSon.id">
                {{grandSon.name}}
              </div>
            </div>
          </div>
        </div>
        </div>
      </div>

    </div>
</template>

<script>

    export default {
        name: "List",
      data(){
          return {
            showList:[],
            showList2:[],
            categorys:[
              {
                id:1,
                name:'category1',
                sons:[
                  {
                    id:11,
                    name:'son1',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:12,
                    name:'son2',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:13,
                    name:'son3',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                ]
              },
              {
                id:2,
                name:'category2',
                sons:[
                  {
                    id:11,
                    name:'son1',
                    grandSon:[
                      {
                        id:104,
                        name:'grandSon'
                      },
                      {
                        id:105,
                        name:'grandSon'
                      },
                      {
                        id:105,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:12,
                    name:'son2',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:13,
                    name:'son3',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                ]
              },
              {
                id:3,
                name:'category3',
                sons:[
                  {
                    id:11,
                    name:'son1',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:12,
                    name:'son2',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:13,
                    name:'son3',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                ]
              },
              {
                id:4,
                name:'category4',
                sons:[
                  {
                    id:11,
                    name:'son1',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:12,
                    name:'son2',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:13,
                    name:'son3',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                ]
              },
              {
                id:5,
                name:'category5',
                sons:[
                  {
                    id:11,
                    name:'son1',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:12,
                    name:'son2',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:13,
                    name:'son3',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                ]
              },
              {
                id:6,
                name:'category6',
                sons:[
                  {
                    id:11,
                    name:'son1',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:12,
                    name:'son2',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:13,
                    name:'son3',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                ]
              },
              {
                id:7,
                name:'category6',
                sons:[
                  {
                    id:11,
                    name:'son1',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:12,
                    name:'son2',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                  {
                    id:13,
                    name:'son3',
                    grandSon:[
                      {
                        id:101,
                        name:'grandSon'
                      },
                      {
                        id:102,
                        name:'grandSon'
                      },
                      {
                        id:103,
                        name:'grandSon'
                      }
                    ]
                  },
                ]
              },
            ]
          }
      },
      methods:{
        show(index){
          console.log("index:"+index);
          console.log(this.showList);
          if(this.showList[index] != undefined){
            this.$set(this.showList,index,!this.showList[index]);
            //this.showList.splice(index,1,!this.showList[index])
          }else{
            this.$set(this.showList,index,true)
            //this.showList.splice(index,1,true)
            //初始化showList2中的当前索引的数组
            this.$set(this.showList2,index,[])
          }
          console.log(this.showList[index]);
        },
        show2(index,index2){
          if(this.showList2[index][index2]==undefined){
            this.$set(this.showList2[index],index2,true)
          }else{
            this.$set(this.showList2[index],index2,!this.showList2[index][index2])
          }
        }
      }
    }
</script>

<style scoped>

</style>
